<#
.SYNOPSIS
RNG Ops v3 — opt-in dev runner. Starts Pocketbase + Vite in parallel.

.DESCRIPTION
Spawns pocketbase.exe (background, HTTP on :8090) and Vite dev server
(foreground, HTTP on :5174). Pocketbase logs interleave with Vite's in
the same console. Ctrl+C in the foreground stops Vite and cleanly
terminates the Pocketbase background process via a try/finally guard.

.WHY HTTP-ONLY (not HTTPS)
PB 0.37.x's HTTPS path uses certmagic, which is ACME/Let's-Encrypt-
oriented; there is no `--cert-file` / `--key-file` flag on `pocketbase
serve` that would let dev.ps1 hand it the mkcert pair generated by
mkcert-setup.ps1. The dev box never serves iPads directly during HMR
work, and the dev service worker is deliberately skipped by
sw-register.ts when import.meta.env.DEV is true. Production at-event
deployment on the LAN is Phase 5 work — see the post-Phase-1 todo for
v3/scripts/serve.ps1, which will revisit HTTPS via certmagic config or
OnServe pb_hooks programmatic cert injection. The certs in v3/certs/
generated by mkcert-setup.ps1 are durable artifacts waiting for that.

.WHEN TO RUN
Day-to-day Phase 1+ development with HMR. Both servers come up fast,
both shut down cleanly on Ctrl+C.

.WHEN NOT TO RUN
- At-event production. This script runs Vite dev with HMR, which is
  not the production bundle. Phase 5's serve.ps1 will run pocketbase
  serving the built pb_public/ artifact for the real workflow.
- Inside CI / non-interactive automation. The script foregrounds Vite
  for log visibility and traps Ctrl+C; there's no exit signal in
  non-interactive mode.

.SIDE EFFECTS
- Spawns pocketbase.exe as a child process. PB writes to ./pb_data/
  (created if absent) at the repo root.
- If node_modules/ is missing in v3/, runs `npm install` once before
  starting Vite. First-run network access required for that case.

.HOW TO UNDO / CLEAN UP
- Ctrl+C in the dev console. Both servers exit; child PB process is
  terminated by the script's finally block.
- If Ctrl+C is bypassed (e.g., console window force-closed), a stray
  pocketbase.exe may remain. Kill via Task Manager or:
    Get-Process pocketbase | Stop-Process -Force

.HOW TO RUN
From any directory:
    pwsh.exe -File v3\scripts\dev.ps1
If your box has Restricted execution policy:
    pwsh.exe -ExecutionPolicy Bypass -File v3\scripts\dev.ps1
#>

$ErrorActionPreference = 'Stop'

# Paths anchored from script location.
$scriptRoot = $PSScriptRoot
$v3Root     = Split-Path -Parent $scriptRoot
$repoRoot   = Split-Path -Parent $v3Root
$pbExe      = Join-Path $repoRoot 'pocketbase.exe'

# 1. Verify pocketbase.exe is present.
if (-not (Test-Path $pbExe)) {
    Write-Host "ERROR: pocketbase.exe not found at $pbExe" -ForegroundColor Red
    Write-Host "Place pocketbase.exe at the repo root before running this script." -ForegroundColor Red
    exit 1
}

# 2. Verify v3/node_modules; install if missing.
$nodeModules = Join-Path $v3Root 'node_modules'
if (-not (Test-Path $nodeModules)) {
    Write-Host "node_modules missing in v3/. Running npm install ..." -ForegroundColor Yellow
    Push-Location $v3Root
    try {
        npm install
        if ($LASTEXITCODE -ne 0) {
            Write-Host "ERROR: npm install exited with code $LASTEXITCODE." -ForegroundColor Red
            exit $LASTEXITCODE
        }
    } finally {
        Pop-Location
    }
}

# 3. Start Pocketbase (HTTP only — see header section "WHY HTTP-ONLY").
Write-Host ""
Write-Host "Starting Pocketbase (HTTP) at http://0.0.0.0:8090 ..." -ForegroundColor Cyan
Write-Host "  Admin UI:  http://localhost:8090/_/"               -ForegroundColor Cyan
Write-Host "  Data dir:  $(Join-Path $repoRoot 'pb_data')"        -ForegroundColor Cyan

$pbProcess = Start-Process -FilePath $pbExe `
    -ArgumentList @('serve', '--http=0.0.0.0:8090') `
    -WorkingDirectory $repoRoot `
    -NoNewWindow -PassThru

# 4. Foreground Vite. try/finally guarantees PB cleanup on Ctrl+C or
#    any other foreground exit (uncaught error, npm-side crash).
try {
    Write-Host ""
    Write-Host "Starting Vite dev server at http://localhost:5174 ..." -ForegroundColor Cyan
    Write-Host "  Press Ctrl+C in this console to stop both servers."   -ForegroundColor Cyan
    Write-Host ""
    Push-Location $v3Root
    try {
        npm run dev
    } finally {
        Pop-Location
    }
}
finally {
    Write-Host ""
    Write-Host "Stopping Pocketbase (PID $($pbProcess.Id)) ..." -ForegroundColor Yellow
    if ($pbProcess -and -not $pbProcess.HasExited) {
        Stop-Process -Id $pbProcess.Id -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Done." -ForegroundColor Green
}
